Add components check script in dir-install
Signed-off-by: Shivesh Abhishek <shankeyshivesh@gmail.com>

diff --git a/stages/director-install/TCID-DIR-INSTALL-ON-LOCAL-HP b/stages/director-install/TCID-DIR-INSTALL-ON-LOCAL-HP
--- a/stages/director-install/TCID-DIR-INSTALL-ON-LOCAL-HP
+++ b/stages/director-install/TCID-DIR-INSTALL-ON-LOCAL-HP
@@ -18,24 +18,24 @@ node() {
 
   # Setting up DOP_URL variable
 
-  DOP_URL=https://$(kubectl get nodes -o wide --no-headers | awk {'print $6'} | awk 'NR==2'):30380
+  DOP_URL=http://$(kubectl get nodes -o wide --no-headers | awk {'print $6'} | awk 'NR==2'):30380
   echo -e "\n DOP URL: $DOP_URL"
 
   #####################################
   ##           Deploy DOP            ##
   #####################################
 
-  echo -e "\n[ Cloning director-charts-internal repo ]\n"
+  # echo -e "\n[ Cloning director-charts-internal repo ]\n"
 
   # git clone https://$GITHUB_USERNAME:$GITHUB_PASSWORD@github.com/mayadata-io/director-charts-internal.git
 
-  cd director-charts-internal
+  # cd director-charts-internal
 
-  echo -e "\n[ Get DOP release version ]-------------------------------------\n"
+  echo -e "\n[ Print DOP release version ]-------------------------------------\n"
   echo -e "Release Version: $RELEASE\n"
 
   # Get into latest release directory of helm chart
-  cd "$RELEASE"/director
+  # cd "$RELEASE"/director
 
   # Create secret having maya-init repo access
   kubectl create secret docker-registry directoronprem-registry-secret --docker-server=registry.mayadata.io --docker-username=$RELEASE_USERNAME --docker-password=$RELEASE_PASSWORD
@@ -43,13 +43,18 @@ node() {
   # Create clusterrolebinding
   kubectl create clusterrolebinding kube-admin --clusterrole cluster-admin --serviceaccount=kube-system:default
 
-  # Replace storageClass to be used to openebs-hostpath in values.yaml
-  # sed 's/storageClass: standard/storageClass: openebs-hostpath/' -i ./values.yaml
-  # cat values.yaml
-
+  # add directoronprem in local repository
+  helm repo add directoronprem https://charts.mayadata.io/
+  
   # Apply helm chart
   # helm install --name dop . --set server.url=$DOP_URL --set nginx-ingress.controller.kind=Deployment --set nginx-ingress.controller.service.enabled=true
-  helm install --repo=https://charts.mayadata.io/ dop --set type.installopenebs=false --set server.url=$DOP_URL --set nginx-ingress.controller.kind=Deployment --set nginx-ingress.controller.service.enabled=true
+  helm install --name dop directoronprem/oep-charts-internal --set type.installopenebs=false --set server.url=$DOP_URL --set server.release=$RELEASE --set nginx-ingress.controller.kind=Deployment --set nginx-ingress.controller.service.enabled=true
+  
+  echo -e "Get the changed values from chart\n"
+  helm get values dop -n director > values.yaml
+
+  echo -e "Changed values in values.yaml\n"
+  cat values.yaml
 
   # Dump Director On-Prem pods
   echo -e "\n[ Dumping Director On-Prem components ]\n"
@@ -63,8 +68,24 @@ node() {
   sleep 540
 
   #Run Components health check
-  chmod 755 ./stages/director-install/components-health-check.sh
-  ./stages/director-install/components-health-check.sh
+  echo -e "\n************************ Running basic-sanity tests ***********************************\n"
+  bash oep-e2e/scripts/director-health-check.sh
+
+  # If any of the above check fails, then fail this job
+  if [ $(cat result.txt | grep -ic fail) != 0 ];then
+    testResult="Fail"
+    echo -e "\nTest Result: $testResult\n"
+    # if [[ $branch_name == "oep-release" ]]; then
+    #   python3 oep-e2e/utils/result_update.py --job_id "$job_id" --stage "$stage" --test_desc "$test_desc" --test_result "$testResult" --time_stamp "$current_time" --token "$gittoken" --test_name "$test_name" --job_name "$test_name" --platform "konvoy"
+    # fi
+    exit 1
+  else
+    testResult="Pass"
+    echo -e "\nTest Result: $testResult\n"
+    # if [[ $branch_name == "oep-release" ]]; then
+    #   python3 oep-e2e/utils/result_update.py --job_id "$job_id" --stage "$stage" --test_desc "$test_desc" --test_result "$testResult" --time_stamp "$current_time" --token "$gittoken" --test_name "$test_name" --job_name "$test_name" --platform "konvoy"
+    # fi
+  fi
 
   #List pods
   kubectl get pods
